      - name: Commit Results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # 不管什么文件夹，直接添加当前目录下所有新增和修改的文件
          git add -A
          
          # 检查是否有文件真的被改动或增加了
          if ! git diff --cached --quiet; then
            git commit -m "Update scraped results"
            git push origin main
          else
            echo "警告：Python脚本没有生成任何新数据或文件，没有什么可以提交的！"
          fi
